const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();}
const demoId=100000001,user=tg?.initDataUnsafe?.user,telegramId=user?.id||demoId,firstName=user?.first_name||"Грибник";const screen=document.getElementById("screen");
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const d=await r.json();if(!r.ok)throw Error(d.detail||"Ошибка");return d}
function money(n){return new Intl.NumberFormat("ru-RU").format(n)} function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
async function refresh(){const u=await api(`/api/user/${telegramId}`);hello.textContent=u.first_name;coins.textContent=money(u.coins);level.textContent=u.level;energy.textContent=u.energy;maxEnergy.textContent=u.max_energy;weight.textContent=u.total_weight.toFixed(1);capacity.textContent=u.basket_capacity;return u}
function showForest(){screen.innerHTML=`<div class="card hero"><div class="mushroom">🍄</div><h2>Берёзовая роща</h2><p class="muted">Начальная локация для поиска.</p><button class="btn" onclick="search('quick')">👀 БЫСТРЫЙ ПОИСК · 1 ⚡</button><button class="btn secondary" onclick="search('careful')">🔎 ТЩАТЕЛЬНЫЙ ПОИСК · 2 ⚡</button><button class="btn secondary" onclick="search('expedition')">🧭 ЭКСПЕДИЦИЯ · 5 ⚡</button></div>`}
async function search(mode){screen.innerHTML=`<div class="card hero"><div class="mushroom">🔎</div><h2>Ищем...</h2><p>Лес шумит...</p></div>`;try{const r=await api('/api/search',{method:'POST',body:JSON.stringify({telegram_id:telegramId,first_name:firstName,location_id:1,mode})});await refresh();screen.innerHTML=`<div class="card hero"><div class="mushroom">${r.rarity.includes('Редкий')?'✨🍄✨':'🍄'}</div><div>${r.rarity}</div><h2>${esc(r.mushroom)}</h2><div class="notice">${esc(r.quality)} · ⚖️ ${r.weight} г</div><p>💰 <b>+${money(r.price)}</b> · ⭐ <b>+${r.xp} XP</b></p>${r.new_find?'<div class="notice">📖 Новая запись!</div>':''}<button class="btn" onclick="search('${mode}')">🍄 ИСКАТЬ ЕЩЁ</button><button class="btn secondary" onclick="showInventory()">🎒 В КОРЗИНУ</button></div>`}catch(e){screen.innerHTML=`<div class="card hero"><div class="mushroom">😕</div><h2>Не получилось</h2><p>${esc(e.message)}</p><button class="btn" onclick="showForest()">Назад</button></div>`}}
async function showInventory(){const r=await api(`/api/inventory/${telegramId}`);let h=`<div class="card"><h2>🎒 Корзина</h2><p>${r.total_weight.toFixed(1)} / ${r.capacity} кг</p>`;if(!r.items.length)h+='<p class="muted">Корзина пуста.</p>';for(const x of r.items)h+=`<div class="item"><span>🍄 ${esc(x.name)}<br><small>${x.weight} г · ${esc(x.quality)}</small></span><b>💰 ${money(x.price)}</b></div>`;if(r.items.length)h+='<button class="btn" onclick="sellAll()">💰 ПРОДАТЬ ВСЁ</button>';screen.innerHTML=h+'</div>'}
async function sellAll(){const r=await api(`/api/sell-all/${telegramId}`,{method:'POST'});await refresh();screen.innerHTML=`<div class="card hero"><div class="mushroom">💰</div><h2>Грибы проданы</h2><p>Продано: ${r.sold}</p><p>Получено: <b>+${money(r.coins)}</b></p><button class="btn" onclick="showForest()">🍄 В ЛЕС</button></div>`}
async function showLocations(){const ls=await api(`/api/locations/${telegramId}`);let h='<div class="card"><h2>🌲 Карта</h2>';for(const l of ls)h+=`<div class="item"><span><b>${esc(l.name)}</b><br><small>${esc(l.description)}</small></span><span>${l.unlocked?'✅':'🔒'}<br><small>ур. ${l.required_level}</small></span></div>`;screen.innerHTML=h+'</div>'}
function showShop(){screen.innerHTML='<div class="card"><h2>🛒 Магазин</h2><div class="item"><span>🎒 Корзина грибника<br><small>20 кг</small></span><b>💰 1 000</b></div><div class="item"><span>🎒 Большая корзина<br><small>35 кг</small></span><b>💰 4 000</b></div><div class="item"><span>🔪 Грибной нож<br><small>+3% к качеству</small></span><b>💰 2 000</b></div><div class="item"><span>🧭 Компас<br><small>+3% к редкости</small></span><b>💰 5 000</b></div><p class="muted">Покупки подключим в следующем этапе.</p></div>'}
async function showProfile(){const u=await refresh();const prev=100*(u.level-1)*(u.level-1),next=100*u.level*u.level,p=u.level>=100?100:Math.max(0,Math.min(100,(u.xp-prev)/(next-prev)*100));screen.innerHTML=`<div class="card hero"><div class="mushroom">👤</div><h2>${esc(u.first_name)}</h2><p>⭐ Уровень ${u.level}</p><div class="bar"><i style="width:${p}%"></i></div><p>${money(u.xp)} XP</p><p>💰 ${money(u.coins)}</p><p>🎒 ${u.total_weight.toFixed(1)} кг</p></div>`}
refresh().then(showForest)
